site_name: Welcome to my website

nav:
    - Intro: index.md
    - ...

theme:
    name: material
    font:
        text: Helvetica
    features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top=
    - content.code.annotate # 
    - content.tabs.link

    palette: # 
     - scheme: default
       primary: teal green
       accent: red
       toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode 
     - scheme: default
       primary: green
       accent: red
       toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
    - stylesheets/extra.css
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css



plugins:
    - search
    - awesome-pages:
        collapse_single_pages: true
        strict: false

markdown_extensions:
    - footnotes
    - toc:
        permalink: "#"
    - attr_list
    - md_in_html
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ampunkboyx
      name: Visit ampunkboyx Github profile
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/mwlite/in/ahmad-afif-8b63a3229
      name: Contact ampunkboyx on Linkedin
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aku.afif/
      name: Follow ampunkboyx on Instagram   